server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  output:
    ansi:
      enabled: always
  application:
    name: demo-logback

log:
  env: dev
  level: INFO
  path: /var/Amazon/logs/xqk
  type: message
